CREATE DATABASE maindb CHARACTER SET 'utf8';

USE maindb;

CREATE TABLE Product (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name_product VARCHAR(100) NOT NULL,
    id_category SMALLINT NOT NULL,
    nutri_score CHAR(1) NOT NULL,
    description_product VARCHAR(200) NOT NULL,
    link_url VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Favorite (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_product_replaced SMALLINT NOT NULL,
    id_product_replacing SMALLINT NOT NULL,
    date_creation_favorite DATETIME NOT NULL,
    PRIMARY KEY (request_number)
)
ENGINE=INNODB;

CREATE TABLE Store (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Category (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    category_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
)
ENGINE=INNODB;

CREATE TABLE Stores_products (
    id_product SMALLINT UNSIGNED NOT NULL,
    id_store SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id_product, id_store),
)
ENGINE=INNODB;